export enum ProductSort {
  BESTSELLING = 'BEST SELLING',
  LOW_HIGH = 'PRICE LOW TO HIGH',
  HIGH_LOW = 'PRICE HIGH TO LOW',
  A_Z = 'ALPHABETICALLY, A-Z',
  Z_A = 'ALPHABETICALLY, Z-A',
  OLD_NEW = 'OLD TO NEW',
  NEW_OLD = 'NEW TO OLD',
}
